path_classifiers:
  test:
    - tests
    - cross-checks/rust-checks/tests
    - cross-checks/c-checks/clang-plugin/test
    - cross-checks/rust-checks/rustc-plugin/tests
    - cross-checks/rust-checks/derive-macros/tests
  library:
    - dependencies
    
extraction:
  python:
    python_setup:
      version: 3
      setup_py: false
  cpp:
    prepare:
      packages:
        - python3-psutil
        
    after_prepare:
      - "curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y"

    configure:
      command:
        - "echo Deliberately not running cmake..."
      
    index:
      build_command:
        - "cat /usr/lib/python3/dist-packages/plumbum/__init__.py > /dev/null" # trick to install python3-plumbum
        - "PATH=\"$HOME/.cargo/bin:$PATH\" scripts/build_translator.py"
