path_classifiers:
  test:
    - tests
    - cross-checks/rust-checks/tests
    - cross-checks/c-checks/clang-plugin/test
    - cross-checks/rust-checks/rustc-plugin/tests
    - cross-checks/rust-checks/derive-macros/tests

extraction:
  python_setup:
    requirements_files:
      - scripts/requirements.txt
    version: 3
    setup_py: false
