// Additional cross-check hash function implementations
// that cannot be auto-generated by the clang plugin

unsigned long long xcheck_hash_PyMemberDef(void *x) {
    // TODO
    return 0x123456789ABCDEFULL;
}

unsigned long long xcheck_hash_struct_buf(void *p) {
    return 0xABCDEF12345678ULL;
}
