[package]
name = "c2rust-analysis-rt"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "C2Rust runtime for recording dynamic analysis, targeted by c2rust-instrument and consumed by c2rust-pdg"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0.1"
once_cell = "=1.21.2"
enum_dispatch = "0.3"
fs-err = "2"
crossbeam-queue = "0.3"
crossbeam-utils = "0.8"
