import logging
from pathlib import Path
from typing import Any

import tree_sitter_rust as tsrust
from tree_sitter import Language, Parser

from postprocess.definitions.clang import (
    get_c_ast_as_json,
    get_functions_from_clang_ast,
    is_entry_from_c_file,
)


def get_c_sourcefile(compile_commands, rustfile: Path) -> Path | None:
    c_file_guesses = [rustfile.with_suffix(".c"), rustfile.with_suffix(".C")]

    files = [Path(d["file"]) for d in compile_commands]

    for guess in c_file_guesses:
        if guess in files:
            return guess

    return None


def get_rust_function_spans(rustfile: Path) -> list[dict[str, Any]]:
    language = Language(tsrust.language())
    parser = Parser(language)

    if not rustfile.exists():
        raise FileNotFoundError(f"{rustfile} does not exist")
    if not rustfile.is_file():
        raise NotADirectoryError(f"{rustfile} is not a file")

    try:
        with open(rustfile, "rb") as rust_source:
            source_bytes = rust_source.read()
    except OSError as exc:
        logging.error(f"Failed to read Rust file {rustfile}: {exc}")
        return []

    tree = parser.parse(source_bytes)

    functions = []

    for node in tree.root_node.children:
        if node.type == 'function_item':
            name_node = node.child_by_field_name('name')
            func_name = (source_bytes[
                name_node.start_byte: # type: ignore
                name_node.end_byte    # type: ignore
            ].decode('utf-8'))

            functions.append({
                "name": func_name,
                "start_line": node.start_point[0] + 1, # 0-indexed
                "end_line": node.end_point[0] + 1, # 0-indexed
                "start_byte": node.start_byte,
                "end_byte": node.end_byte
            })

    return functions


def get_c_function_spans(compile_commands: list[dict[str, Any]], c_file: Path):
    cmd = (c for c in compile_commands if c["file"] == str(c_file))
    entry = next(cmd, None)

    assert entry is not None, f"No compile command entry for {c_file}"

    c_fn_asts = get_functions_from_clang_ast(get_c_ast_as_json(entry))

    functions = []
    for fn in c_fn_asts:
        if not is_entry_from_c_file(fn, str(c_file)):
            continue

        loc = fn["loc"]
        if "line" in loc and "col" in loc:
            # usually, path to offset is: range -> begin -> offset
            # sometimes, likely due to the use of macros, path to offset is:
            # range -> begin -> expansionLoc -> offset
            if "offset" not in fn["range"]["begin"]:
                begin_line = fn["range"]["begin"]["expansionLoc"]["line"]
                begin_offset = fn["range"]["begin"]["expansionLoc"]["offset"]
            else:
                begin_line = fn["loc"]["line"]
                begin_offset = fn["range"]["begin"]["offset"]

            # TODO: are there cases where path to end offset/line differs?
            end_line = fn["range"]["end"]["line"]
            end_offset = fn["range"]["end"]["offset"]

            functions.append({
                "name": fn["name"],
                "start_line": begin_line,
                "start_byte": begin_offset,
                "end_line": end_line,
                "end_byte": end_offset,
            })

    return functions


def get_function_span_pairs(
        compile_commands: list[dict[str, Any]],
        rust_file: Path
    )-> list[tuple[dict[str, Any], dict[str, Any]]]:
    """Get pairs of Rust and C function spans for the given Rust file."""

    rust_fn_spans = get_rust_function_spans(rust_file)

    # drop synthetic main function generated by c2rust transpiler
    rust_fn_spans = filter(lambda fn: fn['name'] != 'main', rust_fn_spans)
    c_file = get_c_sourcefile(compile_commands, rust_file)
    if not c_file:
        logging.info(f"No corresponding C source file found for {rust_file}")
        return []

    c_fn_spans = get_c_function_spans(compile_commands, c_file)
    c_fn_spans = {fn['name']: fn for fn in c_fn_spans}

    pairs = []
    for rust_fn in rust_fn_spans:
        name = rust_fn['name']
        assert name != 'main'
        if name == 'main_0':
            name = 'main'

        if name in c_fn_spans:
            c_fn = c_fn_spans[name]
            c_fn['file'] = c_file
            rust_fn['file'] = rust_file
            pairs.append((rust_fn, c_fn))
        else:
            logging.warning(f"Rust function {name} has no matching C function")

    return pairs

def get_c_comments(code: str) -> list[str]:
    """Extract comments from the given C code."""
    from pygments import lex
    from pygments.lexers import CLexer
    from pygments.token import Comment

    comments = []
    for tok_type, tok_value in lex(code, CLexer()):
        # NOTE: Not including Preproc comments here, as they are not typical comments
        if tok_type in Comment and tok_type not in Comment.Preproc:
            # Keep exactly what appears, including delimiters (//, /* */)
            comments.append(tok_value)
    return comments
