#!/bin/bash
set -e

# Set up a `docs` directory for mkdocs to build from.  Currently we copy over
# all .md and .png files in the repo, preserving directory structure so that
# relative links still work.
rm -rf docs
mkdir -p docs
(cd ..; git ls-files -co --exclude-standard \*.md \*.png |
    xargs manual/copy-files.sh manual/docs)

cp SUMMARY.md docs/SUMMARY.md


# Run scripts for autogenerated documentation files

# `genfile <name> <cmd...>`:
# Run <cmd...>, sending stdout to docs/_generated/<name>
genfile() {
    local file="docs/_generated/$1"
    shift 1
    mkdir -vp "$(dirname "$file")"
    "$@" >"$file"
}


emptysection() {
    genfile $1 cat <<EOF
# $2
Use table of contents to navigate subsections.
EOF
}

emptysection examples.md Examples
emptysection translator.md Translator


# Actually build the HTML docs.
mdbook build


# Work around mdbook bug with linking to files named README.md.
# Files named `README.md` get rendered as `index.html`, but links don't get
# fixed up accordingly (they still point to `README.html`).  Our workaround is
# to copy every `index.html` file under the name `README.html`.
find book -name index.html | while read file; do
    cp -nv "$file" "$(dirname "$file")/README.html"
done

