[package]
name = "c2rust-macros"
version = "0.21.0"
authors = ["Stephen Crane <sjc@immunant.com>", "The C2Rust Project Developers <c2rust@immunant.com>"]
edition = "2021"
description = "Procedural macro support crate for C2Rust"
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits", "visit"] }
