.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ROBOTFINDSKITTEN 6 "November 26, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
robotfindskitten \- robotfindskitten
.SH SYNOPSIS
.B robotfindskitten
.RI [ number ]
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBrobotfindskitten\fP is a Zen simulation that was originally submitted to an art contest.  The goal is to find kitten among a number of non-kitten items.
.SH OPTIONS
.TP
.B number
Specify the number of non-kitten objects to be used in the game.  Defaults to 20 if not specified explicitly.
.SH SEE ALSO
The program is documented fully by
.IR "robotfindskitten" ,
available via the Info system.
.SH AUTHOR

This manual page was originally written by Nick Moffitt
<nick@zork.net>, for the Debian GNU/Linux system.
