name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
    - name: Lint
      run: cargo clippy -- -Dwarnings
    - name: Format
      run: cargo fmt --check
